sudo: required
install:
- source ./texlive_install.sh
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
script:
- mkdir build
- cd res
- travis_wait 3 pdflatex -output-directory ../build Resume.tex
- travis_wait 3 pdflatex -output-directory ../build Resume_fr.tex
- cd ..

# Deploying
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  file: 
  - ./build/Resume.pdf
  - ./build/Resume_fr.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master